/**
 * De teksten van de instellingen, het zoeken en de sneltoetsen.
 *
 * Twee prefixen: `inst.` voor alles wat in een scherm staat, `regels.` voor de
 * regelengine — die heeft er zoveel en ze hangen zo aan elkaar (een veld, een
 * vergelijking, een handeling, en de zin die daaruit gemaakt wordt) dat ze
 * apart makkelijker terug te vinden zijn.
 *
 * Het zoeken en de sneltoetsen staan onder `inst.` en niet onder een eigen
 * prefix, omdat ze bij deze catalogus horen en een sleutel maar in één bestand
 * mag staan.
 *
 * Wat hier met opzet niet in staat: de namen van velden zoals ze in de
 * database heten. Een regel die op `statusName` werkt blijft op `statusName`
 * werken; wat je op het scherm leest is de vertaling, wat er bewaard wordt is
 * de veldnaam.
 */
export default {

  // ── Het zoeken ─────────────────────────────────────────────────────────
  'inst.zoek.plaatshouder': {
    nl: 'Zoek events, taken, klanten, verslagen',
    en: 'Search events, tasks, customers, minutes',
  },
  'inst.zoek.soort.events': { nl: 'Events', en: 'Events' },
  'inst.zoek.soort.taken': { nl: 'Taken', en: 'Tasks' },
  'inst.zoek.soort.klanten': { nl: 'Klanten', en: 'Customers' },
  'inst.zoek.soort.verslagen': { nl: 'Verslagen', en: 'Minutes' },
  'inst.zoek.soort.mensen': { nl: 'Mensen', en: 'People' },
  'inst.zoek.soort.templates': { nl: 'Templates', en: 'Templates' },
  'inst.zoek.klantfiche': { nl: 'klantfiche openen', en: 'open the customer' },
  'inst.zoek.teamoverleg': { nl: 'teamoverleg', en: 'team meeting' },
  'inst.zoek.overleg_van': { nl: 'Teamoverleg van {datum}', en: 'Team meeting of {datum}' },
  'inst.zoek.punt_een': { nl: '{aantal} punt', en: '{aantal} item' },
  'inst.zoek.punt_meer': { nl: '{aantal} punten', en: '{aantal} items' },
  'inst.zoek.mens_sub': {
    nl: '{aantal} open taken · werklast bekijken',
    en: '{aantal} open tasks · see the workload',
  },
  'inst.zoek.template_sub': { nl: 'Template · {uitleg}', en: 'Template · {uitleg}' },
  'inst.zoek.resultaat_een': { nl: '{aantal} resultaat', en: '{aantal} result' },
  'inst.zoek.resultaat_meer': { nl: '{aantal} resultaten', en: '{aantal} results' },
  'inst.zoek.niets': { nl: 'Niets gevonden voor “{vraag}”.', en: 'Nothing found for “{vraag}”.' },
  'inst.zoek.assistent': { nl: 'Vraag het de assistent', en: 'Ask the assistant' },

  // ── De sneltoetsen ─────────────────────────────────────────────────────
  'inst.sneltoets.zoeken': {
    nl: 'Zoeken in taken, events, klanten en verslagen',
    en: 'Search tasks, events, customers and minutes',
  },
  'inst.sneltoets.schuin': { nl: 'Hetzelfde, met één toets', en: 'The same, with one key' },
  'inst.sneltoets.hulp': { nl: 'Dit lijstje', en: 'This list' },
  'inst.sneltoets.eventbord': { nl: 'Naar het eventbord', en: 'To the event board' },
  'inst.sneltoets.tasks': { nl: 'Naar Tasks', en: 'To Tasks' },
  'inst.sneltoets.dashboard': { nl: 'Naar het dashboard', en: 'To the dashboard' },
  'inst.sneltoets.openensluiten': { nl: 'Naar Openen & sluiten', en: 'To Opening & closing' },
  'inst.sneltoets.assistent': { nl: 'Assistent open of dicht', en: 'Assistant open or shut' },
  'inst.sneltoets.uitleg': {
    nl: 'De losse letters werken alleen als je niet in een veld staat.',
    en: 'The single letters only work when your cursor is not in a field.',
  },

  // ── De instellingenpagina ──────────────────────────────────────────────
  'inst.tab.team': { nl: 'Team & toegang', en: 'Team & access' },
  'inst.tab.pijplijn': { nl: 'Pijplijn', en: 'Pipeline' },
  'inst.tab.templates': { nl: 'Templates', en: 'Templates' },
  'inst.tab.formules': { nl: 'Formules', en: 'Formulas' },
  'inst.tab.lijsten': { nl: 'Concepten & kostenplaatsen', en: 'Concepts & cost centres' },
  'inst.tab.structuur': { nl: 'Ruimtes & lijsten', en: 'Spaces & lists' },
  'inst.tab.merken': { nl: 'Merken & labels', en: 'Brands & labels' },
  'inst.tab.dagelijks': { nl: 'Dagelijkse lijsten', en: 'Daily lists' },
  'inst.tab.regels': { nl: 'Business rules', en: 'Business rules' },

  'inst.kop.beheer': {
    nl: 'Beheer · alleen zichtbaar voor beheerders',
    en: 'Admin · only visible to administrators',
  },
  'inst.kop.geen_toegang': { nl: 'Geen toegang', en: 'No access' },
  'inst.geen_toegang.titel': { nl: 'Alleen voor beheerders', en: 'Administrators only' },
  'inst.geen_toegang.tekst': {
    nl: 'Team, toegang, pijplijn en templates worden beheerd door de eigenaars en beheerders.',
    en: 'Team, access, pipeline and templates are looked after by the owners and administrators.',
  },

  // ── Team & toegang ─────────────────────────────────────────────────────
  'inst.team.sso_uitleg': {
    nl: 'Iedereen meldt aan met een Google-account. JE Plan bewaart geen wachtwoorden; wie uit Google verdwijnt, verliest meteen toegang.',
    en: 'Everyone signs in with a Google account. JE Plan keeps no passwords; whoever disappears from Google loses access straight away.',
  },
  'inst.team.enige_methode': { nl: 'Enige methode', en: 'The only way in' },
  'inst.team.automatisch': { nl: 'Automatisch toegang voor', en: 'Automatic access for' },
  'inst.team.domein_plaatshouder': { nl: '+ domein toevoegen', en: '+ add a domain' },
  'inst.team.domein_label': { nl: 'Domein toevoegen', en: 'Add a domain' },
  'inst.team.andere_accounts': {
    nl: 'Andere Google-accounts (bv. gmail.com) komen enkel binnen met een uitnodiging.',
    en: 'Other Google accounts (gmail.com, say) only get in by invitation.',
  },
  'inst.team.actief': { nl: '{aantal} actief', en: '{aantal} active' },
  'inst.team.rol_van': { nl: 'Rol van {wie}', en: 'Role of {wie}' },
  'inst.team.eigen_rol': {
    nl: 'Je eigen rol kun je niet wijzigen.',
    en: 'You cannot change your own role.',
  },
  'inst.team.afdeling_van': { nl: 'Afdeling van {wie}', en: 'Department of {wie}' },
  'inst.team.geen_afdeling': { nl: 'Geen afdeling', en: 'No department' },
  'inst.team.uurtarief_plaatshouder': { nl: '€ per uur', en: '€ per hour' },
  'inst.team.uurtarief': { nl: 'Intern uurtarief', en: 'Internal hourly rate' },
  'inst.team.zelf_archiveren': { nl: 'Jezelf archiveren kan niet.', en: 'You cannot archive yourself.' },
  'inst.team.uitnodigen': { nl: 'Iemand uitnodigen', en: 'Invite someone' },
  'inst.team.google_account': { nl: 'Google-account', en: 'Google account' },
  'inst.team.uitnodigen_knop': { nl: 'Uitnodigen', en: 'Invite' },
  'inst.team.uitgenodigd': {
    nl: '{wie} kan nu aanmelden met Google.',
    en: '{wie} can sign in with Google now.',
  },
  'inst.team.wacht': { nl: 'Wacht', en: 'Waiting' },
  'inst.team.intrekken': { nl: 'Uitnodiging intrekken', en: 'Withdraw the invitation' },
  'inst.team.gearchiveerd': { nl: 'Gearchiveerd', en: 'Archived' },
  'inst.team.gearchiveerd_uitleg': {
    nl: 'Kunnen niet aanmelden. Hun uren en taken blijven bewaard.',
    en: 'Cannot sign in. Their hours and tasks are kept.',
  },
  'inst.team.niemand_gearchiveerd': { nl: 'Niemand gearchiveerd.', en: 'Nobody archived.' },
  'inst.team.uren_bewaard': { nl: 'Uren en taken bewaard', en: 'Hours and tasks kept' },
  'inst.team.heractiveren': { nl: 'Heractiveren', en: 'Reactivate' },

  // De afdelingen van de dagelijkse lijsten, zoals ze op het scherm staan.
  'inst.afdeling.iedereen': { nl: 'Iedereen', en: 'Everyone' },
  'inst.afdeling.verantwoordelijke': { nl: 'Verantwoordelijke', en: 'Supervisor' },
  'inst.afdeling.keuken': { nl: 'Keuken', en: 'Kitchen' },
  'inst.afdeling.zaal': { nl: 'Zaal', en: 'Front of house' },

  // ── De pijplijn ────────────────────────────────────────────────────────
  'inst.pijplijn.geen_lijst': {
    nl: 'Er is nog geen eventlijst met de statuspijplijn.',
    en: 'There is no event list with the status pipeline yet.',
  },
  'inst.pijplijn.kop': { nl: 'Statuspijplijn events', en: 'Event status pipeline' },
  'inst.pijplijn.uitleg': {
    nl: 'Namen aanpassen mag; de volgorde volgt het verloop van aanvraag tot betaling.',
    en: 'You may rename them; the order follows the run from request to payment.',
  },
  'inst.pijplijn.statusnaam': { nl: 'Statusnaam', en: 'Status name' },
  'inst.pijplijn.regel.request': {
    nl: 'Vereist: klant, datum, gasten, offerte',
    en: 'Needs: customer, date, guests, quote',
  },
  'inst.pijplijn.regel.facturatie': { nl: 'Start facturatie-opvolging', en: 'Starts invoice follow-up' },
  'inst.pijplijn.regel.archief': { nl: 'Naar archief', en: 'To the archive' },

  // ── Templates ──────────────────────────────────────────────────────────
  'inst.tpl.nieuw': { nl: 'Nieuw template', en: 'New template' },
  'inst.tpl.verwijder_vraag': { nl: 'Template "{naam}" verwijderen?', en: 'Delete template "{naam}"?' },
  'inst.tpl.naam': { nl: 'Naam template', en: 'Template name' },
  'inst.tpl.icoon': { nl: 'Icoon', en: 'Icon' },
  'inst.tpl.dupliceren': { nl: 'Dupliceren', en: 'Duplicate' },
  'inst.tpl.taken': { nl: 'Taken', en: 'Tasks' },
  'inst.tpl.deadlines': {
    nl: 'Deadlines tellen terug vanaf de eventdatum; een negatief aantal valt erná.',
    en: 'Deadlines count back from the event date; a negative number falls after it.',
  },
  'inst.tpl.taak': { nl: 'Taak', en: 'Task' },
  'inst.tpl.standaard_voor': { nl: 'Standaard voor', en: 'Goes to' },
  'inst.tpl.dagen_vooraf': { nl: 'Dagen vooraf', en: 'Days before' },
  'inst.tpl.prioriteit': { nl: 'Prioriteit', en: 'Priority' },
  'inst.tpl.herhaling': { nl: 'Herhaling', en: 'Repeat' },
  'inst.tpl.taak_verwijderen': { nl: 'Taak verwijderen', en: 'Delete task' },
  'inst.tpl.subtaken': { nl: 'Subtaken', en: 'Subtasks' },
  'inst.tpl.subtaak_plaatshouder': { nl: '+ subtaak en Enter', en: '+ subtask and Enter' },
  'inst.tpl.subtaak_label': { nl: 'Subtaak toevoegen', en: 'Add a subtask' },
  'inst.tpl.taak_toevoegen': { nl: 'Taak toevoegen', en: 'Add a task' },
  'inst.tpl.telling': {
    nl: '{taken} taken · {subs} subtaken',
    en: '{taken} tasks · {subs} subtasks',
  },
  'inst.tpl.telling_wie': {
    nl: '{taken} taken · {subs} subtaken · {wie}',
    en: '{taken} tasks · {subs} subtasks · {wie}',
  },
  'inst.icoon.feest': { nl: 'Feest', en: 'Party' },
  'inst.icoon.team': { nl: 'Team', en: 'Team' },
  'inst.icoon.eten': { nl: 'Eten', en: 'Food' },
  'inst.icoon.muziek': { nl: 'Muziek', en: 'Music' },
  'inst.icoon.techniek': { nl: 'Techniek', en: 'Technical' },
  'inst.icoon.kalender': { nl: 'Kalender', en: 'Calendar' },
  'inst.icoon.document': { nl: 'Document', en: 'Document' },
  'inst.prio.normaal': { nl: 'Normaal', en: 'Normal' },
  'inst.prio.hoog': { nl: 'Hoog', en: 'High' },
  'inst.prio.urgent': { nl: 'Urgent', en: 'Urgent' },
  'inst.herhaling.eenmalig': { nl: 'Eenmalig', en: 'One-off' },
  'inst.herhaling.wekelijks': { nl: 'Wekelijks', en: 'Weekly' },
  'inst.herhaling.na3': { nl: 'Na 3 dagen', en: 'After 3 days' },

  // ── Concepten & kostenplaatsen ─────────────────────────────────────────
  'inst.concept.kop': { nl: 'Concepten', en: 'Concepts' },
  'inst.concept.uitleg': {
    nl: 'Uit staat niet meer bij nieuwe events en in de filters.',
    en: 'Switched off, it no longer turns up on new events or in the filters.',
  },
  'inst.concept.event_een': { nl: '{aantal} event', en: '{aantal} event' },
  'inst.concept.event_meer': { nl: '{aantal} events', en: '{aantal} events' },
  'inst.concept.actief': { nl: '{naam} actief', en: '{naam} active' },
  'inst.kosten.kop': { nl: 'Kostenplaatsen', en: 'Cost centres' },
  'inst.kosten.uitleg': { nl: 'Tijd boeken zonder event.', en: 'Logging time without an event.' },
  'inst.kosten.wisselen': {
    nl: 'Wisselen tussen billable en intern',
    en: 'Switch between billable and internal',
  },
  'inst.kosten.billable': { nl: 'Billable', en: 'Billable' },
  'inst.kosten.intern': { nl: 'Intern', en: 'Internal' },
  'inst.kosten.plaatshouder': { nl: '+ kostenplaats en Enter', en: '+ cost centre and Enter' },
  'inst.kosten.label': { nl: 'Kostenplaats toevoegen', en: 'Add a cost centre' },

  // ── Ruimtes & lijsten ──────────────────────────────────────────────────
  'inst.struct.ruimte_aangemaakt': { nl: 'Ruimte aangemaakt.', en: 'Space created.' },
  'inst.struct.lijst_aangemaakt': {
    nl: 'Lijst aangemaakt, met vier standaardkolommen.',
    en: 'List created, with four standard columns.',
  },
  'inst.struct.lijstnaam': { nl: 'Lijstnaam', en: 'List name' },
  'inst.struct.soort_social': { nl: 'social', en: 'social' },
  'inst.struct.soort_taken': { nl: 'taken', en: 'tasks' },
  'inst.struct.kolommen': { nl: 'Kolommen', en: 'Columns' },
  'inst.struct.terughalen': { nl: 'Terughalen', en: 'Bring back' },
  'inst.struct.archiveer_vraag': {
    nl: 'Lijst archiveren? De taken blijven bewaard.',
    en: 'Archive the list? The tasks are kept.',
  },
  'inst.struct.nieuwe_ruimte': { nl: 'Nieuwe ruimte', en: 'New space' },
  'inst.struct.naam': { nl: 'Naam', en: 'Name' },
  'inst.struct.nieuwe_lijst': { nl: 'Nieuwe lijst', en: 'New list' },
  'inst.struct.ruimte': { nl: 'Ruimte', en: 'Space' },
  'inst.struct.kies_ruimte': { nl: 'Kies een ruimte…', en: 'Choose a space…' },
  'inst.struct.soort': { nl: 'Soort', en: 'Kind' },
  'inst.struct.takenbord': { nl: 'Takenbord', en: 'Task board' },
  'inst.struct.socialcontent': { nl: 'Socialcontent', en: 'Social content' },

  // ── Merken & labels ────────────────────────────────────────────────────
  'inst.merk.kop': { nl: 'Merken', en: 'Brands' },
  'inst.merk.kleur_van': { nl: 'Kleur van {naam}', en: 'Colour of {naam}' },
  'inst.merk.naam': { nl: 'Merknaam', en: 'Brand name' },
  'inst.merk.toegevoegd': { nl: 'Merk toegevoegd.', en: 'Brand added.' },
  'inst.merk.kleur': { nl: 'Kleur', en: 'Colour' },
  'inst.merk.nieuw': { nl: 'Nieuw merk', en: 'New brand' },
  'inst.label.kop': { nl: 'Labels', en: 'Labels' },
  'inst.label.nieuw': { nl: 'Nieuw label', en: 'New label' },
  'inst.label.geen': { nl: 'Nog geen labels.', en: 'No labels yet.' },
  'inst.label.samenvoegen': { nl: 'samenvoegen', en: 'merge' },
  'inst.label.samenvoegen_knop': { nl: 'Samenvoegen', en: 'Merge' },
  'inst.label.verwijderen': { nl: 'Label verwijderen', en: 'Delete label' },
  'inst.label.verwijder_vraag': {
    nl: 'Label "{naam}" verwijderen? De taken houden de naam, maar de kleur verdwijnt. Samenvoegen is meestal wat je wil.',
    en: 'Delete label "{naam}"? The tasks keep the name, but the colour goes. Merging is usually what you want.',
  },
  'inst.label.samenvoeg_titel': { nl: '"{naam}" samenvoegen', en: 'Merge "{naam}"' },
  'inst.label.wordt': { nl: 'Wordt', en: 'Becomes' },
  'inst.label.wordt_hint': {
    nl: 'Het label hierboven verdwijnt; de taken krijgen deze naam.',
    en: 'The label above goes; the tasks take this name.',
  },
  'inst.label.tellen': { nl: 'Aan het tellen…', en: 'Counting…' },
  'inst.label.geen_taak': {
    nl: 'Er staat geen taak op "{naam}". Het label verdwijnt, verder verandert er niets.',
    en: 'No task carries "{naam}". The label goes, nothing else changes.',
  },
  'inst.label.taken_een': {
    nl: '{aantal} taak draagt "{van}" en krijgt "{naar}".',
    en: '{aantal} task carries "{van}" and takes "{naar}".',
  },
  'inst.label.taken_meer': {
    nl: '{aantal} taken dragen "{van}" en krijgen "{naar}".',
    en: '{aantal} tasks carry "{van}" and take "{naar}".',
  },
  'inst.label.samengevoegd_leeg': {
    nl: 'Samengevoegd; er stond geen taak op dat label.',
    en: 'Merged; no task carried that label.',
  },
  'inst.label.samengevoegd_een': { nl: 'Samengevoegd — {aantal} taak verplaatst.', en: 'Merged — {aantal} task moved.' },
  'inst.label.samengevoegd_meer': { nl: 'Samengevoegd — {aantal} taken verplaatst.', en: 'Merged — {aantal} tasks moved.' },

  // ── Dagelijkse lijsten ─────────────────────────────────────────────────
  'inst.lijst.uitleg': {
    nl: 'Wat het personeel bij het openen en sluiten afvinkt. Per punt staat wie het ziet en hoe vaak het terugkomt; een punt dat vandaag niet moet, staat er vandaag ook niet.',
    en: 'What the staff tick off at opening and closing. Each item says who sees it and how often it comes back; an item that is not due today does not show today.',
  },
  'inst.lijst.uit': { nl: ' (uit)', en: ' (off)' },
  'inst.lijst.geen': { nl: 'Er is nog geen lijst.', en: 'There is no list yet.' },
  'inst.lijst.nieuwe': { nl: 'Nieuwe lijst', en: 'New list' },
  'inst.lijst.nieuwe_plaatshouder': {
    nl: 'Bijvoorbeeld: weekendcontrole terras',
    en: 'For instance: weekend check of the terrace',
  },
  'inst.lijst.aangemaakt': { nl: 'Lijst aangemaakt.', en: 'List created.' },
  'inst.lijst.naam': { nl: 'Naam van de lijst', en: 'Name of the list' },
  'inst.lijst.soort': { nl: 'Soort lijst', en: 'Kind of list' },
  'inst.lijst.soort_open': { nl: 'Bij het openen', en: 'At opening' },
  'inst.lijst.soort_close': { nl: 'Bij het sluiten', en: 'At closing' },
  'inst.lijst.soort_other': { nl: 'Los van een dienst', en: 'Apart from a shift' },
  'inst.lijst.uit_gebruik': { nl: 'uit gebruik', en: 'out of use' },
  'inst.lijst.terughalen': { nl: 'Terughalen', en: 'Bring back' },
  'inst.lijst.uit_nemen': { nl: 'Uit gebruik nemen', en: 'Take out of use' },
  'inst.lijst.uit_nemen_vraag': {
    nl: 'Lijst uit gebruik nemen? De afgevinkte dagen blijven bewaard.',
    en: 'Take the list out of use? The days already ticked off are kept.',
  },
  'inst.lijst.groepsnaam': { nl: 'Naam van de groep', en: 'Name of the group' },
  'inst.lijst.punten': { nl: '{aantal} punten', en: '{aantal} items' },
  'inst.lijst.groep_weg': { nl: 'Groep weg', en: 'Group out' },
  'inst.lijst.groep_weg_vraag': {
    nl: 'Deze groep en al haar punten verwijderen?',
    en: 'Delete this group and every item in it?',
  },
  'inst.lijst.geen_punten': { nl: 'Nog geen punten in deze groep.', en: 'No items in this group yet.' },
  'inst.lijst.punt_erbij': { nl: '+ Punt', en: '+ Item' },
  'inst.lijst.groep_erbij': { nl: '+ Groep', en: '+ Group' },

  // Eén punt
  'inst.punt.plaatshouder': { nl: 'Wat moet er gebeuren?', en: 'What needs doing?' },
  'inst.punt.omschrijving': { nl: 'Omschrijving van het punt', en: 'Description of the item' },
  'inst.punt.klaar': { nl: 'Klaar', en: 'Done' },
  'inst.punt.wijzigen': { nl: 'Wijzigen', en: 'Change' },
  'inst.punt.weg': { nl: 'Weg', en: 'Out' },
  'inst.punt.weg_vraag': {
    nl: 'Dit punt verwijderen? Wat er in het verleden is afgevinkt blijft bewaard.',
    en: 'Delete this item? Whatever was ticked off in the past is kept.',
  },
  'inst.punt.wie': { nl: 'Wie ziet dit punt', en: 'Who sees this item' },
  'inst.punt.hoe_vaak': { nl: 'Hoe vaak', en: 'How often' },
  'inst.punt.hoe_vaak_label': { nl: 'Hoe vaak dit punt terugkomt', en: 'How often this item comes back' },
  'inst.punt.welke_dagen': { nl: 'Op welke dagen', en: 'On which days' },
  'inst.punt.welke_dag': { nl: 'Welke dag', en: 'Which day' },
  'inst.punt.dag_van_maand': { nl: 'Dag van de maand', en: 'Day of the month' },
  'inst.punt.dag_van_maand_hint': {
    nl: 'De 31e schuift naar de laatste dag van de maand.',
    en: 'The 31st slides to the last day of the month.',
  },
  'inst.punt.maand': { nl: 'Maand', en: 'Month' },
  'inst.punt.waarde': { nl: 'Vraagt een waarde', en: 'Asks for a value' },
  'inst.punt.waarde_hint': {
    nl: 'Naast het vinkje, bijvoorbeeld een datum of een temperatuur.',
    en: 'Beside the tick, a date or a temperature for instance.',
  },
  'inst.punt.wat_vraagt': { nl: 'Wat vraagt het', en: 'What it asks' },
  'inst.punt.wat_vraagt_plaatshouder': { nl: 'Laatst vervangen op', en: 'Last replaced on' },
  'inst.punt.eenheid': { nl: 'Eenheid', en: 'Unit' },
  'inst.punt.eenheid_hint': { nl: 'Wat er achter het getal staat.', en: 'What comes after the number.' },
  'inst.punt.grenzen': { nl: 'Grenzen', en: 'Limits' },
  'inst.punt.grenzen_hint': {
    nl: 'Leeg laten betekent: alleen noteren, niet beoordelen.',
    en: 'Left empty means: noted only, not judged.',
  },
  'inst.punt.ondergrens': { nl: 'Ondergrens voor {punt}', en: 'Lower limit for {punt}' },
  'inst.punt.bovengrens': { nl: 'Bovengrens voor {punt}', en: 'Upper limit for {punt}' },
  'inst.punt.min': { nl: 'min', en: 'min' },
  'inst.punt.max': { nl: 'max', en: 'max' },
  'inst.punt.tot': { nl: 'tot', en: 'to' },
  'inst.punt.toelichting': { nl: 'Toelichting', en: 'Note' },
  'inst.punt.toelichting_plaatshouder': {
    nl: 'Waar het hangt, welke code, waar je op let…',
    en: 'Where it hangs, which code, what to watch for…',
  },
  'inst.punt.code_verborgen': {
    nl: 'De toelichting bevat een code en blijft verborgen tot je erop klikt',
    en: 'The note holds a code and stays hidden until you click it',
  },

  // De keuzelijsten van een punt; de sleutels blijven wat ze in de database zijn.
  'inst.freq.dagelijks': { nl: 'Elke dag', en: 'Every day' },
  'inst.freq.weekdag': { nl: 'Op bepaalde dagen', en: 'On set days' },
  'inst.freq.wekelijks': { nl: 'Eén keer per week', en: 'Once a week' },
  'inst.freq.maandelijks': { nl: 'Eén keer per maand', en: 'Once a month' },
  'inst.freq.kwartaal': { nl: 'Elk kwartaal', en: 'Every quarter' },
  'inst.freq.jaarlijks': { nl: 'Eén keer per jaar', en: 'Once a year' },
  'inst.dag.ma': { nl: 'ma', en: 'Mon' },
  'inst.dag.di': { nl: 'di', en: 'Tue' },
  'inst.dag.wo': { nl: 'wo', en: 'Wed' },
  'inst.dag.do': { nl: 'do', en: 'Thu' },
  'inst.dag.vr': { nl: 'vr', en: 'Fri' },
  'inst.dag.za': { nl: 'za', en: 'Sat' },
  'inst.dag.zo': { nl: 'zo', en: 'Sun' },
  'inst.veldsoort.geen': { nl: 'Geen — alleen afvinken', en: 'None — just a tick' },
  'inst.veldsoort.datum': { nl: 'Een datum', en: 'A date' },
  'inst.veldsoort.getal': { nl: 'Een getal', en: 'A number' },

  // ── Formules ───────────────────────────────────────────────────────────
  'inst.formule.geen': { nl: 'Nog geen formules.', en: 'No formulas yet.' },
  'inst.formule.nieuwe': { nl: 'Nieuwe formule', en: 'New formula' },
  'inst.formule.naam': { nl: 'Naam formule', en: 'Formula name' },
  'inst.formule.verwijder_vraag': {
    nl: 'Formule "{naam}" verwijderen? Archiveren volstaat meestal.',
    en: 'Delete formula "{naam}"? Archiving is usually enough.',
  },
  'inst.formule.prijs_pp': { nl: 'Prijs p.p.', en: 'Price p.p.' },
  'inst.formule.excl_btw': { nl: 'Excl. btw', en: 'Excl. VAT' },
  'inst.formule.vaste_kost': { nl: 'Vaste kost', en: 'Fixed cost' },
  'inst.formule.ongeacht': { nl: 'Ongeacht het aantal', en: 'Whatever the number' },
  'inst.formule.btw_tarief': { nl: 'Btw-tarief', en: 'VAT rate' },
  'inst.formule.taken_template': { nl: 'Taken uit template', en: 'Tasks from template' },
  'inst.formule.actief_label': { nl: 'Formule actief', en: 'Formula active' },
  'inst.formule.gearchiveerd': { nl: 'Gearchiveerd', en: 'Archived' },
  'inst.formule.actief': { nl: 'Actief', en: 'Active' },
  'inst.formule.omschrijving': { nl: 'Omschrijving', en: 'Description' },
  'inst.formule.omschrijving_hint': {
    nl: 'Staat bij de keuze in het scherm Nieuw event',
    en: 'Shows with the choice on the New event screen',
  },
  'inst.formule.vragen': { nl: 'Vragen bij het aanmaken', en: 'Questions when creating' },
  'inst.formule.vragen_sub': {
    nl: 'Het eerste antwoord is wat standaard gekozen staat.',
    en: 'The first answer is the one chosen by default.',
  },
  'inst.formule.vraag': { nl: 'Vraag', en: 'Question' },
  'inst.formule.vraag_verwijderen': { nl: 'Vraag verwijderen', en: 'Delete question' },
  'inst.formule.vraag_toevoegen': { nl: 'Vraag toevoegen', en: 'Add a question' },
  'inst.formule.btw_meerprijs': { nl: 'Btw op deze meerprijs', en: 'VAT on this extra' },
  'inst.formule.btw_zoals': { nl: 'Zoals de formule ({percent}%)', en: 'As the formula ({percent}%)' },
  'inst.formule.antwoord': { nl: 'Antwoord', en: 'Answer' },
  'inst.formule.antwoord_verwijderen': { nl: 'Antwoord verwijderen', en: 'Delete answer' },
  'inst.formule.antwoord_toevoegen': { nl: 'Antwoord toevoegen', en: 'Add an answer' },
  'inst.formule.meerprijs_pp': { nl: 'Meerprijs per persoon voor {antwoord}', en: 'Extra per person for {antwoord}' },
  'inst.formule.meerprijs_vast': { nl: 'Vaste meerprijs voor {antwoord}', en: 'Fixed extra for {antwoord}' },
  'inst.formule.per_persoon': { nl: '+ per persoon', en: '+ per person' },
  'inst.formule.vast': { nl: '+ vast', en: '+ fixed' },
  'inst.formule.bestelregels': { nl: 'Bestelregels', en: 'Order lines' },
  'inst.formule.bestelregels_sub': {
    nl: 'Per persoon, of vast. Er wordt altijd per verpakking naar boven afgerond.',
    en: 'Per person, or fixed. Always rounded up to whole packs.',
  },
  'inst.formule.artikel': { nl: 'Artikel', en: 'Item' },
  'inst.formule.categorie': { nl: 'Categorie', en: 'Category' },
  'inst.formule.eenheid': { nl: 'Eenheid', en: 'Unit' },
  'inst.formule.pp_kort': { nl: 'P.p.', en: 'P.p.' },
  'inst.formule.vast_kort': { nl: 'Vast', en: 'Fixed' },
  'inst.formule.per_verpakking': { nl: 'Per verpakking', en: 'Per pack' },
  'inst.formule.verpakking': { nl: 'Verpakking', en: 'Pack' },
  'inst.formule.hoort_bij': { nl: 'Hoort bij', en: 'Belongs to' },
  'inst.formule.per_persoon_label': { nl: 'Per persoon', en: 'Per person' },
  'inst.formule.vaste_hoeveelheid': { nl: 'Vaste hoeveelheid', en: 'Fixed quantity' },
  'inst.formule.eenheden_verpakking': { nl: 'Eenheden per verpakking', en: 'Units per pack' },
  'inst.formule.verpakking_naam': { nl: 'Naam van de verpakking', en: 'Name of the pack' },
  'inst.formule.hoort_bij_label': { nl: 'Hoort bij welk antwoord', en: 'Belongs to which answer' },
  'inst.formule.regel_verwijderen': { nl: 'Bestelregel verwijderen', en: 'Delete order line' },
  'inst.formule.regel_toevoegen': { nl: 'Bestelregel toevoegen', en: 'Add an order line' },
  'inst.formule.altijd': { nl: 'Altijd (kale formule)', en: 'Always (bare formula)' },
  'inst.formule.proef': { nl: 'Proefberekening', en: 'Trial calculation' },
  'inst.formule.proef_sub': {
    nl: 'Met de standaardantwoorden, zoals een nieuw event begint.',
    en: 'With the default answers, the way a new event starts.',
  },
  'inst.formule.aantal_personen': { nl: 'Aantal personen', en: 'Number of people' },
  'inst.formule.excl': { nl: '{bedrag} excl.', en: '{bedrag} excl.' },
  'inst.formule.incl': { nl: '{bedrag} incl.', en: '{bedrag} incl.' },
  'inst.formule.btw_regel': { nl: 'btw {percent}%: {bedrag}', en: 'VAT {percent}%: {bedrag}' },
  'inst.btw.6': { nl: '6% — afhaal en logies', en: '6% — takeaway and lodging' },
  'inst.btw.12': { nl: '12% — bereide maaltijd ter plaatse', en: '12% — meal prepared on site' },
  'inst.btw.21': { nl: '21% — drank, verhuur, diensten', en: '21% — drink, hire, services' },

  // ── De regelengine ─────────────────────────────────────────────────────
  // De sleutels hieronder horen bij de namen die in `functions/rule-schema.js`
  // staan. Die namen zelf blijven wat ze zijn — een regel die op `statusName`
  // werkt blijft op `statusName` werken; alleen wat je leest hangt aan de taal.

  'regels.kop.uitleg': {
    nl: 'Een regel doet iets op het moment dat er iets verandert — bijvoorbeeld: alles wat op {status} komt, wordt van Elke en van niemand anders. Het kan over taken en events gaan, maar net zo goed over klanten, social posts, afvinklijsten, urenboekingen en profielen. De regels draaien op de server, dus ook wanneer iemand anders de kaart versleept.',
    en: 'A rule does something the moment something changes — say: everything that reaches {status} becomes Elke’s and nobody else’s. It can be about tasks and events, but just as well about customers, social posts, checklists, time entries and profiles. The rules run on the server, so they also fire when someone else drags the card.',
  },
  'regels.leeg': {
    nl: 'Er staat nog geen enkele regel. Niets gebeurt automatisch.',
    en: 'There is not a single rule yet. Nothing happens by itself.',
  },
  'regels.aanzetten': { nl: 'Aanzetten', en: 'Switch on' },
  'regels.uitzetten': { nl: 'Uitzetten', en: 'Switch off' },
  'regels.verwijder_vraag': { nl: 'Regel verwijderen?', en: 'Delete the rule?' },
  'regels.staat_aan': { nl: 'Regel staat aan.', en: 'The rule is on.' },
  'regels.nieuwe_regel': { nl: 'Nieuwe regel', en: 'New rule' },
  'regels.nieuwe_tabel': { nl: 'Nieuwe beslissingstabel', en: 'New decision table' },
  'regels.regel_aanzetten': { nl: 'Regel aanzetten', en: 'Switch the rule on' },
  'regels.weg_ermee': { nl: 'Weg ermee', en: 'Bin it' },
  'regels.wat_deden': { nl: 'Wat de regels deden', en: 'What the rules did' },
  'regels.naam': { nl: 'Naam van de regel', en: 'Name of the rule' },
  'regels.badge_tabel': { nl: 'tabel', en: 'table' },
  'regels.badge_uit': { nl: 'uit', en: 'off' },
  'regels.waarover': { nl: 'Waarover', en: 'About what' },
  'regels.waarover_label': { nl: 'Waarover gaat de regel', en: 'What the rule is about' },
  'regels.als': { nl: 'Als', en: 'When' },
  'regels.aanleiding': { nl: 'Aanleiding', en: 'Trigger' },
  'regels.welk_veld': { nl: 'Welk veld', en: 'Which field' },
  'regels.veld_wijzigt': { nl: 'Veld dat wijzigt', en: 'Field that changes' },
  'regels.op_lijst_label': { nl: 'Op lijst', en: 'On list' },
  'regels.elke_lijst': { nl: 'Elke lijst', en: 'Any list' },
  'regels.alleen_als': { nl: 'Alleen als', en: 'Only when' },
  'regels.dan': { nl: 'Dan', en: 'Then' },

  // De voorwaardenboom
  'regels.combineren': { nl: 'Voorwaarden combineren', en: 'Combining the conditions' },
  'regels.groep.all': { nl: 'alles hieronder klopt', en: 'everything below is true' },
  'regels.groep.any': { nl: 'één van deze klopt', en: 'one of these is true' },
  'regels.groep.none': { nl: 'geen van deze klopt', en: 'none of these is true' },
  'regels.voorwaarde_erbij': { nl: 'Voorwaarde erbij', en: 'Add a condition' },
  'regels.groep_erbij': { nl: 'Groep erbij', en: 'Add a group' },
  'regels.groep_weg': { nl: 'Groep weg', en: 'Group out' },
  'regels.geen_voorwaarden': {
    nl: 'Geen voorwaarden — de regel vuurt op haar aanleiding alleen.',
    en: 'No conditions — the rule fires on its trigger alone.',
  },
  'regels.veld': { nl: 'Veld', en: 'Field' },
  'regels.vergelijking': { nl: 'Vergelijking', en: 'Comparison' },
  'regels.waarde': { nl: 'Waarde', en: 'Value' },
  'regels.weg': { nl: 'Weg', en: 'Out' },

  // Het invulveld
  'regels.datum_label': { nl: 'Datum', en: 'Date' },
  'regels.datum_soort': { nl: '{label} — soort', en: '{label} — kind' },
  'regels.datum_dagen_label': { nl: '{label} — aantal dagen', en: '{label} — number of days' },
  'regels.datum_dag_label': { nl: '{label} — dag', en: '{label} — day' },
  'regels.vanaf_vandaag': { nl: 'vanaf vandaag', en: 'from today' },
  'regels.vaste_dag': { nl: 'een vaste dag', en: 'a set day' },
  'regels.dagen': { nl: 'dagen', en: 'days' },
  'regels.ja': { nl: 'ja', en: 'yes' },
  'regels.nee': { nl: 'nee', en: 'no' },
  'regels.kies': { nl: 'Kies…', en: 'Choose…' },
  'regels.bestaat_niet_meer': { nl: '{waarde} (bestaat niet meer)', en: '{waarde} (no longer exists)' },

  // De acties
  'regels.actie_toevoegen': { nl: 'Actie toevoegen', en: 'Add an action' },
  'regels.actie_toevoegen_leeg': { nl: 'Actie toevoegen…', en: 'Add an action…' },
  'regels.actie_onbekend': {
    nl: 'Onbekende actie — ze wordt overgeslagen.',
    en: 'Unknown action — it gets skipped.',
  },
  'regels.en': { nl: 'En', en: 'And' },
  'regels.manier_toewijzen': { nl: 'Manier van toewijzen', en: 'Way of assigning' },
  'regels.modus.set': { nl: 'wordt de enige', en: 'becomes the only one' },
  'regels.modus.add': { nl: 'komt erbij', en: 'comes along' },
  'regels.datum_erbij': { nl: 'Datum erbij', en: 'Date with it' },
  'regels.datum_bij_label': { nl: 'Datum bij het label', en: 'Date on the label' },
  'regels.welke_dag': { nl: 'Welke dag', en: 'Which day' },
  'regels.label_woord': { nl: 'Label', en: 'Label' },
  'regels.om_vijf': {
    nl: 'Om 17.00, zodat het niet meteen te laat staat',
    en: 'At 17.00, so it does not read as late straight away',
  },

  // De beslissingstabel
  'regels.kolommen': { nl: 'Kolommen', en: 'Columns' },
  'regels.kolom_veld': { nl: 'Kolom {nummer} — veld', en: 'Column {nummer} — field' },
  'regels.kolom_vergelijking': { nl: 'Kolom {nummer} — vergelijking', en: 'Column {nummer} — comparison' },
  'regels.kolom_weg': { nl: 'Kolom weg', en: 'Column out' },
  'regels.kolom_erbij': { nl: 'Kolom erbij', en: 'Add a column' },
  'regels.rij': { nl: 'Rij', en: 'Row' },
  'regels.rij_naam': { nl: 'Naam van rij {nummer}', en: 'Name of row {nummer}' },
  'regels.rij_naam_plaatshouder': { nl: 'naam', en: 'name' },
  'regels.rij_cel': { nl: 'Rij {nummer}, {kolom}', en: 'Row {nummer}, {kolom}' },
  'regels.kolom_woord': { nl: 'kolom', en: 'column' },
  'regels.rij_erbij': { nl: 'Rij erbij', en: 'Add a row' },
  'regels.tabel_uitleg': {
    nl: 'Van boven naar beneden gelezen tot er een rij past — die rij wint, de rest wordt niet meer bekeken. Een lege cel betekent “maakt niet uit”.',
    en: 'Read top to bottom until a row fits — that row wins, the rest is not looked at. An empty cell means “does not matter”.',
  },

  // Het logboek
  'regels.log.leeg': {
    nl: 'Nog niets gevuurd. Zodra een regel iets wijzigt, staat hier wat en waarom.',
    en: 'Nothing fired yet. As soon as a rule changes something, what and why shows up here.',
  },
  'regels.log.een_regel': { nl: 'een regel', en: 'a rule' },
  'regels.log.rij': { nl: '{naam} ({rij})', en: '{naam} ({rij})' },
  'regels.log.wijzigde': { nl: '{wie} wijzigde {velden}', en: '{wie} changed {velden}' },

  // ── De woordenschat van de regels ──────────────────────────────────────
  'regels.ent.task': { nl: 'Taken en events', en: 'Tasks and events' },
  'regels.ent.customer': { nl: 'Klanten', en: 'Customers' },
  'regels.ent.socialPost': { nl: 'Social posts', en: 'Social posts' },
  'regels.ent.checklistRun': { nl: 'Afvinklijsten', en: 'Checklists' },
  'regels.ent.timeEntry': { nl: 'Urenboekingen', en: 'Time entries' },
  'regels.ent.profile': { nl: 'Profielen', en: 'Profiles' },
  'regels.art.task': { nl: 'een taak', en: 'a task' },
  'regels.art.customer': { nl: 'een klant', en: 'a customer' },
  'regels.art.socialPost': { nl: 'een post', en: 'a post' },
  'regels.art.checklistRun': { nl: 'een dag', en: 'a day' },
  'regels.art.timeEntry': { nl: 'een boeking', en: 'an entry' },
  'regels.art.profile': { nl: 'een profiel', en: 'a profile' },

  'regels.veld.task.statusName': { nl: 'Status', en: 'Status' },
  'regels.veld.task.listId': { nl: 'Lijst', en: 'List' },
  'regels.veld.task.title': { nl: 'Titel', en: 'Title' },
  'regels.veld.task.description': { nl: 'Omschrijving', en: 'Description' },
  'regels.veld.task.priority': { nl: 'Prioriteit', en: 'Priority' },
  'regels.veld.task.tags': { nl: 'Labels', en: 'Labels' },
  'regels.veld.task.assignees': { nl: 'Toegewezen aan', en: 'Assigned to' },
  'regels.veld.task.customerName': { nl: 'Klant', en: 'Customer' },
  'regels.veld.task.brandId': { nl: 'Merk', en: 'Brand' },
  'regels.veld.task.dueDate': { nl: 'Vervaldag', en: 'Due date' },
  'regels.veld.task.startDate': { nl: 'Startdag', en: 'Start date' },
  'regels.veld.task.eventDate': { nl: 'Dag van het event', en: 'Day of the event' },
  'regels.veld.task.budget': { nl: 'Budget', en: 'Budget' },
  'regels.veld.task.quoteAmount': { nl: 'Offertebedrag', en: 'Quoted amount' },
  'regels.veld.task.pax': { nl: 'Aantal gasten', en: 'Number of guests' },
  'regels.veld.task.eventType': { nl: 'Soort event', en: 'Kind of event' },
  'regels.veld.task.formule': { nl: 'Formule', en: 'Formula' },
  'regels.veld.task.archived': { nl: 'Gearchiveerd', en: 'Archived' },
  'regels.veld.task.open': { nl: 'Nog open', en: 'Still open' },
  'regels.veld.task.parentId': { nl: 'Hoort onder een event', en: 'Sits under an event' },

  'regels.veld.customer.name': { nl: 'Naam', en: 'Name' },
  'regels.veld.customer.vatNumber': { nl: 'Btw-nummer', en: 'VAT number' },
  'regels.veld.customer.email': { nl: 'E-mail', en: 'Email' },
  'regels.veld.customer.phone': { nl: 'Telefoon', en: 'Phone' },
  'regels.veld.customer.city': { nl: 'Gemeente', en: 'Town' },
  'regels.veld.customer.postalCode': { nl: 'Postcode', en: 'Postcode' },
  'regels.veld.customer.brandId': { nl: 'Merk', en: 'Brand' },
  'regels.veld.customer.tags': { nl: 'Labels', en: 'Labels' },
  'regels.veld.customer.notes': { nl: 'Notities', en: 'Notes' },
  'regels.veld.customer.archived': { nl: 'Gearchiveerd', en: 'Archived' },

  'regels.veld.socialPost.title': { nl: 'Titel', en: 'Title' },
  'regels.veld.socialPost.status': { nl: 'Status', en: 'Status' },
  'regels.veld.socialPost.channels': { nl: 'Kanalen', en: 'Channels' },
  'regels.veld.socialPost.assigneeId': { nl: 'Van wie', en: 'Whose' },
  'regels.veld.socialPost.reviewState': { nl: 'Review', en: 'Review' },
  'regels.veld.socialPost.reviewerId': { nl: 'Reviewer', en: 'Reviewer' },
  'regels.veld.socialPost.brandId': { nl: 'Merk', en: 'Brand' },
  'regels.veld.socialPost.publishAt': { nl: 'Publicatiemoment', en: 'Publication moment' },
  'regels.veld.socialPost.taskId': { nl: 'Hangt aan event', en: 'Hangs from an event' },
  'regels.veld.socialPost.caption': { nl: 'Tekst', en: 'Copy' },

  'regels.veld.checklistRun.checklistName': { nl: 'Lijst', en: 'List' },
  'regels.veld.checklistRun.day': { nl: 'Dag', en: 'Day' },
  'regels.veld.checklistRun.weekend': { nl: 'Weekend', en: 'Weekend' },
  'regels.veld.checklistRun.doneCount': { nl: 'Afgevinkt', en: 'Ticked off' },
  'regels.veld.checklistRun.totalCount': { nl: 'Aantal punten', en: 'Number of items' },
  'regels.veld.checklistRun.participants': { nl: 'Wie vinkte af', en: 'Who ticked off' },
  'regels.veld.checklistRun.notes': { nl: 'Opmerking', en: 'Note' },
  'regels.veld.checklistRun.closedAt': { nl: 'Afgesloten op', en: 'Closed on' },
  'regels.veld.checklistRun.flagged': { nl: 'Gemarkeerd', en: 'Flagged' },

  'regels.veld.timeEntry.profileId': { nl: 'Van wie', en: 'Whose' },
  'regels.veld.timeEntry.listId': { nl: 'Lijst', en: 'List' },
  'regels.veld.timeEntry.taskTitle': { nl: 'Taak', en: 'Task' },
  'regels.veld.timeEntry.description': { nl: 'Omschrijving', en: 'Description' },
  'regels.veld.timeEntry.billable': { nl: 'Factureerbaar', en: 'Billable' },
  'regels.veld.timeEntry.durationSeconds': { nl: 'Duur in seconden', en: 'Duration in seconds' },
  'regels.veld.timeEntry.day': { nl: 'Dag', en: 'Day' },
  'regels.veld.timeEntry.month': { nl: 'Maand', en: 'Month' },
  'regels.veld.timeEntry.tags': { nl: 'Labels', en: 'Labels' },

  'regels.veld.profile.email': { nl: 'E-mail', en: 'Email' },
  'regels.veld.profile.fullName': { nl: 'Naam', en: 'Name' },
  'regels.veld.profile.role': { nl: 'Rol', en: 'Role' },
  'regels.veld.profile.department': { nl: 'Afdeling', en: 'Department' },
  'regels.veld.profile.active': { nl: 'Actief', en: 'Active' },
  'regels.veld.profile.hourlyRate': { nl: 'Uurtarief', en: 'Hourly rate' },

  'regels.actie.task.assignees': { nl: 'Toewijzen', en: 'Assign' },
  'regels.actie.task.priority': { nl: 'Prioriteit zetten', en: 'Set the priority' },
  'regels.actie.task.tag': { nl: 'Label toevoegen', en: 'Add a label' },
  'regels.actie.task.dueDate': { nl: 'Vervaldag zetten', en: 'Set the due date' },
  'regels.actie.task.startDate': { nl: 'Startdag zetten', en: 'Set the start date' },
  'regels.actie.customer.brand': { nl: 'Merk toewijzen', en: 'Assign a brand' },
  'regels.actie.customer.tag': { nl: 'Label toevoegen', en: 'Add a label' },
  'regels.actie.customer.archive': { nl: 'Archiveren', en: 'Archive' },
  'regels.actie.socialPost.assignee': { nl: 'Toewijzen', en: 'Assign' },
  'regels.actie.socialPost.postStatus': { nl: 'Status zetten', en: 'Set the status' },
  'regels.actie.socialPost.review': { nl: 'Review vragen aan', en: 'Ask a review from' },
  'regels.actie.socialPost.publishAt': { nl: 'Publicatiemoment zetten', en: 'Set the publication moment' },
  'regels.actie.checklistRun.flag': { nl: 'Markeren met opmerking', en: 'Flag with a note' },
  'regels.actie.checklistRun.followUp': { nl: 'Laten opvolgen door', en: 'Have it followed up by' },
  'regels.actie.timeEntry.billable': { nl: 'Factureerbaar zetten', en: 'Set billable' },
  'regels.actie.timeEntry.tag': { nl: 'Label toevoegen', en: 'Add a label' },
  'regels.actie.profile.department': { nl: 'Afdeling zetten', en: 'Set the department' },
  'regels.noun.toegewezene': { nl: 'toegewezene', en: 'assignee' },
  'regels.noun.opvolger': { nl: 'opvolger', en: 'follow-up' },

  'regels.op.is': { nl: 'is', en: 'is' },
  'regels.op.isNot': { nl: 'is niet', en: 'is not' },
  'regels.op.contains': { nl: 'bevat', en: 'contains' },
  'regels.op.notContains': { nl: 'bevat niet', en: 'does not contain' },
  'regels.op.gt': { nl: 'is groter dan', en: 'is greater than' },
  'regels.op.gte': { nl: 'is minstens', en: 'is at least' },
  'regels.op.lt': { nl: 'is kleiner dan', en: 'is smaller than' },
  'regels.op.lte': { nl: 'is hoogstens', en: 'is at most' },
  'regels.op.before': { nl: 'valt voor', en: 'falls before' },
  'regels.op.after': { nl: 'valt na', en: 'falls after' },
  'regels.op.isTrue': { nl: 'is aan', en: 'is on' },
  'regels.op.isFalse': { nl: 'is uit', en: 'is off' },
  'regels.op.empty': { nl: 'is leeg', en: 'is empty' },
  'regels.op.notEmpty': { nl: 'is ingevuld', en: 'is filled in' },

  'regels.prio.1': { nl: 'Urgent', en: 'Urgent' },
  'regels.prio.2': { nl: 'Hoog', en: 'High' },
  'regels.prio.3': { nl: 'Normaal', en: 'Normal' },
  'regels.prio.4': { nl: 'Laag', en: 'Low' },
  'regels.rol.owner': { nl: 'Eigenaar', en: 'Owner' },
  'regels.rol.admin': { nl: 'Beheerder', en: 'Administrator' },
  'regels.rol.member': { nl: 'Teamlid', en: 'Team member' },
  'regels.rol.staff': { nl: 'Personeel', en: 'Staff' },

  // ── De regel in gewone taal ────────────────────────────────────────────
  'regels.trigger.changed': { nl: 'er iets wijzigt aan {wat}', en: 'something changes on {wat}' },
  'regels.trigger.created': { nl: '{wat} wordt aangemaakt', en: '{wat} is created' },
  'regels.zin.datum': { nl: 'een datum', en: 'a date' },
  'regels.zin.vandaag': { nl: 'vandaag', en: 'today' },
  'regels.zin.over_een': { nl: 'over {aantal} dag', en: 'in {aantal} day' },
  'regels.zin.over_meer': { nl: 'over {aantal} dagen', en: 'in {aantal} days' },
  'regels.zin.geleden_een': { nl: '{aantal} dag geleden', en: '{aantal} day ago' },
  'regels.zin.geleden_meer': { nl: '{aantal} dagen geleden', en: '{aantal} days ago' },
  'regels.zin.op_datum': { nl: 'op {datum}', en: 'on {datum}' },
  'regels.zin.veld_weg': { nl: 'een veld dat niet bestaat', en: 'a field that does not exist' },
  'regels.zin.op_weg': { nl: '{veld} — onbekende vergelijking', en: '{veld} — unknown comparison' },
  'regels.zin.voorwaarde_kaal': { nl: '{veld} {vergelijking}', en: '{veld} {vergelijking}' },
  'regels.zin.voorwaarde': { nl: '{veld} {vergelijking} “{waarde}”', en: '{veld} {vergelijking} “{waarde}”' },
  'regels.zin.en': { nl: ' en ', en: ' and ' },
  'regels.zin.of': { nl: ' of ', en: ' or ' },
  'regels.zin.niet': { nl: 'niet {zin}', en: 'not {zin}' },
  'regels.zin.niets': { nl: 'er gebeurt niets', en: 'nothing happens' },
  'regels.zin.niemand': { nl: 'niemand', en: 'nobody' },
  'regels.zin.komt_erbij': { nl: '{wie} komt erbij als {rol}', en: '{wie} comes along as {rol}' },
  'regels.zin.wordt_enige': { nl: '{wie} wordt de enige {rol}', en: '{wie} becomes the only {rol}' },
  'regels.zin.label': { nl: 'het label “{naam}” komt erbij', en: 'the label “{naam}” is added' },
  'regels.zin.label_datum': {
    nl: 'het label “{naam}” komt erbij met {datum} erbij',
    en: 'the label “{naam}” is added with {datum} on it',
  },
  'regels.zin.label_leeg': { nl: 'er komt een label bij', en: 'a label is added' },
  'regels.zin.actie_datum': { nl: '{handeling} — {datum}', en: '{handeling} — {datum}' },
  'regels.zin.actie_ja_nee': { nl: '{handeling}: {waarde}', en: '{handeling}: {waarde}' },
  'regels.zin.actie_leeg': { nl: '{handeling} wordt leeggemaakt', en: '{handeling} is emptied' },
  'regels.zin.op_lijst': { nl: ' op {lijst}', en: ' on {lijst}' },
  'regels.zin.komt_bij': { nl: 'Komt er {wat}{waar} bij', en: 'When {wat} is created{waar}' },
  'regels.zin.wijzigt': {
    nl: 'Wijzigt {veld} van {wat}{waar}',
    en: 'When the {veld} of {wat}{waar} changes',
  },
  'regels.zin.wijzigt_kaal': { nl: 'Wijzigt {wat}{waar}', en: 'When {wat}{waar} changes' },
  'regels.zin.met_voorwaarde': { nl: '{wanneer}, en {voorwaarde}', en: '{wanneer}, and {voorwaarde}' },
  'regels.zin.tabel_een': {
    nl: '{kop}, dan wordt de tabel van boven naar beneden gelezen — {aantal} rij, de eerste die past wint.',
    en: '{kop}, then the table is read top to bottom — {aantal} row, the first that fits wins.',
  },
  'regels.zin.tabel_meer': {
    nl: '{kop}, dan wordt de tabel van boven naar beneden gelezen — {aantal} rijen, de eerste die past wint.',
    en: '{kop}, then the table is read top to bottom — {aantal} rows, the first that fits wins.',
  },
  'regels.zin.zonder_actie': {
    nl: '{kop}, dan gebeurt er nog niets — voeg een actie toe.',
    en: '{kop}, then nothing happens yet — add an action.',
  },
  'regels.zin.dan': { nl: '{kop}, dan {gevolgen}.', en: '{kop}, then {gevolgen}.' },

  // ── Waarschuwingen bij een regel ───────────────────────────────────────
  'regels.waarschuwing.zonder_actie': { nl: 'Zonder actie doet {waar} niets.', en: 'Without an action {waar} does nothing.' },
  'regels.waarschuwing.de_regel': { nl: 'de regel', en: 'the rule' },
  'regels.waarschuwing.rij': { nl: 'rij {nummer}', en: 'row {nummer}' },
  'regels.waarschuwing.actie_weg': {
    nl: 'De actie “{actie}” bestaat niet op {entiteit} — ze wordt overgeslagen.',
    en: 'The action “{actie}” does not exist on {entiteit} — it gets skipped.',
  },
  'regels.waarschuwing.kies_wie': { nl: 'Kies wie.', en: 'Choose who.' },
  'regels.waarschuwing.kies_label': { nl: 'Kies een label.', en: 'Choose a label.' },
  'regels.waarschuwing.kies_datum': { nl: 'Kies een datum.', en: 'Choose a date.' },
  'regels.waarschuwing.vul_in': { nl: 'Vul “{wat}” in.', en: 'Fill in “{wat}”.' },
  'regels.waarschuwing.kies_veld': {
    nl: 'Kies het veld dat de regel wakker maakt.',
    en: 'Choose the field that wakes the rule.',
  },
  'regels.waarschuwing.lege_groep': {
    nl: 'Een lege groep voorwaarden telt niet mee.',
    en: 'An empty group of conditions does not count.',
  },
  'regels.waarschuwing.veld_weg': {
    nl: 'Een voorwaarde staat op een veld dat niet bestaat.',
    en: 'A condition sits on a field that does not exist.',
  },
  'regels.waarschuwing.vergelijking_kan_niet': {
    nl: '“{veld}” kan niet zo vergeleken worden.',
    en: '“{veld}” cannot be compared that way.',
  },
  'regels.waarschuwing.vul_waarde': { nl: 'Vul een waarde in bij “{veld}”.', en: 'Fill in a value at “{veld}”.' },
  'regels.waarschuwing.status_lijst': {
    nl: 'Deze status staat niet op die lijst — de regel vuurt nooit.',
    en: 'That status is not on that list — the rule never fires.',
  },
  'regels.waarschuwing.status_nergens': {
    nl: 'Geen enkele lijst heeft deze status — de regel vuurt nooit.',
    en: 'No list has that status — the rule never fires.',
  },
  'regels.waarschuwing.tabel_kolom': {
    nl: 'Een tabel heeft minstens één kolom nodig.',
    en: 'A table needs at least one column.',
  },
  'regels.waarschuwing.tabel_rijen': {
    nl: 'Een tabel zonder rijen doet niets.',
    en: 'A table without rows does nothing.',
  },
}
