/**
 * De teksten van het logboek.
 *
 * De veldnamen zijn die van de database vertaald naar wat het team ze noemt:
 * `quoteAmount` is "offertebedrag", `assignees` zijn "uitvoerders". Een logboek
 * dat je moet ontcijferen wordt niet gelezen.
 */
export default {
  'logboek.titel': { nl: 'Logboek', en: 'Audit log' },
  'logboek.uitleg': {
    nl: 'Wie heeft wat veranderd, in de hele tool. De regels worden door de server geschreven en zijn niet te wijzigen.',
    en: 'Who changed what, across the whole tool. The entries are written by the server and cannot be edited.',
  },
  'logboek.leeg': { nl: 'leeg', en: 'empty' },
  'logboek.ja': { nl: 'ja', en: 'yes' },
  'logboek.nee': { nl: 'nee', en: 'no' },
  'logboek.onbekend': { nl: 'Onbekend', en: 'Unknown' },
  'logboek.niets': { nl: 'Niets gevonden', en: 'Nothing found' },
  'logboek.niets_uitleg': {
    nl: 'Er is niets dat aan deze filters voldoet. Probeer een ruimere periode.',
    en: 'Nothing matches these filters. Try a wider period.',
  },
  'logboek.nog_niets': { nl: 'Het logboek is nog leeg', en: 'The audit log is still empty' },
  'logboek.nog_niets_uitleg': {
    nl: 'Zodra er iets verandert, komt het hier te staan.',
    en: 'As soon as something changes, it appears here.',
  },
  'logboek.regel_een': { nl: '{aantal} regel', en: '{aantal} entry' },
  'logboek.regel_meer': { nl: '{aantal} regels', en: '{aantal} entries' },
  'logboek.iedereen': { nl: 'Iedereen', en: 'Everyone' },
  'logboek.alles': { nl: 'Alles', en: 'Everything' },
  'logboek.zoeken': { nl: 'Zoeken in het logboek', en: 'Search the audit log' },
  'logboek.periode': { nl: 'Periode', en: 'Period' },
  'logboek.periode_week': { nl: 'Deze week', en: 'This week' },
  'logboek.periode_maand': { nl: 'Deze maand', en: 'This month' },
  'logboek.periode_kwartaal': { nl: 'Laatste drie maanden', en: 'Last three months' },
  'logboek.periode_alles': { nl: 'Alles', en: 'Everything' },
  'logboek.exporteer': { nl: 'Exporteren naar CSV', en: 'Export to CSV' },
  'logboek.onzeker': {
    nl: 'Wie het weggooide is niet zeker — dit is wie het als laatste bewerkte.',
    en: 'Who deleted it is not certain — this is who last edited it.',
  },
  'logboek.bewaartermijn': {
    nl: 'Het logboek gaat twee jaar terug. Wat ouder is, wordt maandelijks opgeruimd.',
    en: 'The audit log goes back two years. Anything older is cleared out monthly.',
  },

  // ── De zinnen ──────────────────────────────────────────────────────────
  'logboek.zin.aangemaakt': { nl: '{wie} maakte {soort} {wat} aan', en: '{wie} created {soort} {wat}' },
  'logboek.zin.verwijderd': { nl: '{wie} verwijderde {soort} {wat}', en: '{wie} deleted {soort} {wat}' },
  'logboek.zin.veld': {
    nl: '{wie} wijzigde {veld} van {wat} — van {van} naar {naar}',
    en: '{wie} changed {veld} of {wat} — from {van} to {naar}',
  },
  'logboek.zin.meerdere': {
    nl: '{wie} wijzigde {velden} van {soort} {wat}',
    en: '{wie} changed {velden} of {soort} {wat}',
  },

  // ── De soorten ─────────────────────────────────────────────────────────
  'logboek.soort.taak': { nl: 'taak', en: 'task' },
  'logboek.soort.klant': { nl: 'klant', en: 'customer' },
  'logboek.soort.offerte': { nl: 'offerte', en: 'quote' },
  'logboek.soort.formule': { nl: 'formule', en: 'formula' },
  'logboek.soort.regel': { nl: 'regel', en: 'rule' },
  'logboek.soort.lijst': { nl: 'lijst', en: 'list' },
  'logboek.soort.afvinklijst': { nl: 'afvinklijst', en: 'checklist' },
  'logboek.soort.dienst': { nl: 'dienst', en: 'shift' },
  'logboek.soort.template': { nl: 'template', en: 'template' },
  'logboek.soort.profiel': { nl: 'profiel', en: 'profile' },
  'logboek.soort.instelling': { nl: 'instelling', en: 'setting' },

  // ── De velden ──────────────────────────────────────────────────────────
  'logboek.veld.titel': { nl: 'de titel', en: 'the title' },
  'logboek.veld.naam': { nl: 'de naam', en: 'the name' },
  'logboek.veld.status': { nl: 'de status', en: 'the status' },
  'logboek.veld.deadline': { nl: 'de deadline', en: 'the deadline' },
  'logboek.veld.uitvoerders': { nl: 'de uitvoerders', en: 'the assignees' },
  'logboek.veld.prioriteit': { nl: 'de prioriteit', en: 'the priority' },
  'logboek.veld.archief': { nl: 'het archief', en: 'the archive' },
  'logboek.veld.budget': { nl: 'het budget', en: 'the budget' },
  'logboek.veld.offertebedrag': { nl: 'het offertebedrag', en: 'the quoted amount' },
  'logboek.veld.klant': { nl: 'de klant', en: 'the customer' },
  'logboek.veld.locatie': { nl: 'de locatie', en: 'the venue' },
  'logboek.veld.planning': { nl: 'de planning', en: 'the planning' },
  'logboek.veld.gasten': { nl: 'het aantal gasten', en: 'the number of guests' },
  'logboek.veld.socialstand': { nl: 'de socialstand', en: 'the social stage' },
  'logboek.veld.lijst': { nl: 'de lijst', en: 'the list' },
  'logboek.veld.rol': { nl: 'de rol', en: 'the role' },
  'logboek.veld.actief': { nl: 'de toegang', en: 'access' },
  'logboek.veld.email': { nl: 'het e-mailadres', en: 'the email address' },
  'logboek.veld.afdeling': { nl: 'de afdeling', en: 'the department' },
  'logboek.veld.btwnummer': { nl: 'het btw-nummer', en: 'the VAT number' },
  'logboek.veld.telefoon': { nl: 'het telefoonnummer', en: 'the phone number' },
  'logboek.veld.adres': { nl: 'het adres', en: 'the address' },
  'logboek.veld.kolommen': { nl: 'de kolommen', en: 'the columns' },
  'logboek.veld.onderdelen': { nl: 'de onderdelen', en: 'the sections' },
  'logboek.veld.prijs_pp': { nl: 'de prijs per persoon', en: 'the price per person' },
  'logboek.veld.vaste_prijs': { nl: 'de vaste prijs', en: 'the fixed price' },
  'logboek.veld.btw': { nl: 'het btw-tarief', en: 'the VAT rate' },
  'logboek.veld.opties': { nl: 'de opties', en: 'the options' },
  'logboek.veld.aan': { nl: 'aan of uit', en: 'on or off' },
  'logboek.veld.voorwaarden': { nl: 'de voorwaarden', en: 'the conditions' },
  'logboek.veld.handelingen': { nl: 'de handelingen', en: 'the actions' },
  'logboek.veld.tabel': { nl: 'de beslissingstabel', en: 'the decision table' },
  'logboek.veld.stand': { nl: 'de stand', en: 'the stage' },
  'logboek.veld.regels': { nl: 'de regels', en: 'the lines' },
  'logboek.veld.bedrag': { nl: 'het bedrag', en: 'the amount' },
  'logboek.veld.verstuurd': { nl: 'het versturen', en: 'the sending' },
  'logboek.veld.soort': { nl: 'de soort', en: 'the kind' },
  'logboek.veld.datum': { nl: 'de datum', en: 'the date' },
  'logboek.veld.start': { nl: 'het beginuur', en: 'the start time' },
  'logboek.veld.einde': { nl: 'het einduur', en: 'the end time' },
  'logboek.veld.pauze': { nl: 'de pauze', en: 'the break' },
  'logboek.veld.notitie': { nl: 'de notitie', en: 'the note' },
  'logboek.veld.persoon': { nl: 'de persoon', en: 'the person' },
  'logboek.veld.domeinen': { nl: 'de toegelaten domeinen', en: 'the allowed domains' },
  'logboek.veld.taken': { nl: 'de taken', en: 'the tasks' },
  'logboek.veld.entiteit': { nl: 'waarop de regel werkt', en: 'what the rule works on' },
  'logboek.veld.aanleiding': { nl: 'de aanleiding', en: 'the trigger' },
  'logboek.veld.werkruimte': { nl: 'de naam van de werkruimte', en: 'the workspace name' },
  'logboek.veld.kostenplaatsen': { nl: 'de kostenplaatsen', en: 'the cost centres' },
}
